[pytest]
testpaths = Backend/db_adapters/test Backend/handlers/test
python_files = test_*.py *_test.py *.test.py
norecursedirs = Backend/archive .venv
pythonpath = . Backend
addopts = --import-mode=importlib
