export const mockNodes = [
  {
    id: '1',
    parent_id: null,
    branch_id: 'main',
    action: 'ADD_TABLE',
    params: 'Student',
    status: 'SUCCESS',
    confidence: 0.96,
    row_count: 100,
    execution_time_ms: 0.8,
    failure_reason: null,
    checkpoint_id: null,
    created_at: '10:00',
    is_active_branch: true,
    clarification: null,
  },
  {
    id: '2',
    parent_id: '1',
    branch_id: 'main',
    action: 'ADD_TABLE',
    params: 'Enrollment',
    status: 'SUCCESS',
    confidence: 0.93,
    row_count: 240,
    execution_time_ms: 0.9,
    failure_reason: null,
    checkpoint_id: null,
    created_at: '10:01',
    is_active_branch: true,
    clarification: null,
  },
  {
    id: '3',
    parent_id: '2',
    branch_id: 'main',
    action: 'ADD_JOIN',
    params: 'Student → Enrollment',
    status: 'SUCCESS',
    confidence: 0.91,
    row_count: 180,
    execution_time_ms: 1.4,
    failure_reason: null,
    checkpoint_id: 'cp-1',
    created_at: '10:02',
    is_active_branch: true,
    clarification: null,
  },
  {
    id: '4',
    parent_id: '3',
    branch_id: 'failed-branch',
    action: 'ADD_FILTER',
    params: 'CGPA > 8',
    status: 'FAILED',
    confidence: 0.88,
    row_count: 0,
    execution_time_ms: 0.4,
    failure_reason: 'COLUMN_INVALID: column CGPA not found',
    checkpoint_id: null,
    created_at: '10:03',
    is_active_branch: false,
    clarification: null,
  },
  {
    id: '5',
    parent_id: '3',
    branch_id: 'active-branch',
    action: 'ADD_FILTER',
    params: 'GPA > 8',
    status: 'SUCCESS',
    confidence: 0.94,
    row_count: 31,
    execution_time_ms: 1.4,
    failure_reason: null,
    checkpoint_id: null,
    created_at: '10:04',
    is_active_branch: true,
    clarification: 'Use GPA instead of CGPA',
  },
  {
    id: '6',
    parent_id: '5',
    branch_id: 'active-branch',
    action: 'HAVING',
    params: 'COUNT(course_id) > 3',
    status: 'SUCCESS',
    confidence: 0.9,
    row_count: 14,
    execution_time_ms: 1.8,
    failure_reason: null,
    checkpoint_id: null,
    created_at: '10:05',
    is_active_branch: true,
    clarification: null,
  },
  {
    id: '7',
    parent_id: '6',
    branch_id: 'active-branch',
    action: 'EXECUTE',
    params: 'Run final query',
    status: 'SUCCESS',
    confidence: 0.97,
    row_count: 14,
    execution_time_ms: 2.1,
    failure_reason: null,
    checkpoint_id: null,
    created_at: '10:06',
    is_active_branch: true,
    clarification: null,
  },
]