export const queryCatalog = [
  {
    id: 'db-university',
    name: 'university.sqlite',
    queries: [
      {
        id: 'q-uni-success',
        title: 'Students with GPA above 8',
        request: 'Students with GPA above 8 enrolled in more than 3 courses',
        status: 'success',
        updated: '2026-10-07 10:06',
        leaf: true,
        nodes: [
          {
            id: '1',
            parent_id: null,
            action: 'SELECT_TABLE',
            params: 'Student',
            status: 'SUCCESS',
            confidence: 0.96,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:00',
            clarification: null,
            sql: 'SELECT * FROM "Student" AS s',
          },
          {
            id: '2',
            parent_id: '1',
            action: 'JOIN',
            params: 'Enrollment ON Student.id = Enrollment.student_id',
            status: 'SUCCESS',
            confidence: 0.94,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:01',
            clarification: null,
            sql: 'SELECT * FROM "Student" AS s JOIN "Enrollment" AS e ON s.id = e.student_id',
          },
          {
            id: '3',
            parent_id: '2',
            action: 'FILTER',
            params: 'CGPA > 8',
            status: 'FAILED',
            confidence: 0.78,
            failure_reason: 'COLUMN_INVALID',
            checkpoint_id: 'cp-1',
            created_at: '10:02',
            clarification: null,
            sql: 'SELECT * FROM "Student" AS s JOIN "Enrollment" AS e ON s.id = e.student_id WHERE s.cgpa > 8',
          },
          {
            id: '4',
            parent_id: '2',
            action: 'FILTER',
            params: 'GPA > 8',
            status: 'SUCCESS',
            confidence: 0.93,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:03',
            clarification: 'Use GPA instead of CGPA',
            sql: 'SELECT * FROM "Student" AS s JOIN "Enrollment" AS e ON s.id = e.student_id WHERE s.gpa > 8',
          },
          {
            id: '5',
            parent_id: '4',
            action: 'GROUP_BY',
            params: 'Student.name',
            status: 'SUCCESS',
            confidence: 0.91,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:04',
            clarification: null,
            sql: 'SELECT s.name, COUNT(e.course_id) AS course_count FROM "Student" AS s JOIN "Enrollment" AS e ON s.id = e.student_id WHERE s.gpa > 8 GROUP BY s.name',
          },
          {
            id: '6',
            parent_id: '5',
            action: 'HAVING',
            params: 'COUNT(course_id) > 3',
            status: 'SUCCESS',
            confidence: 0.9,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:05',
            clarification: null,
            sql: 'SELECT s.name, COUNT(e.course_id) AS course_count FROM "Student" AS s JOIN "Enrollment" AS e ON s.id = e.student_id WHERE s.gpa > 8 GROUP BY s.name HAVING COUNT(e.course_id) > 3',
          },
          {
            id: '7',
            parent_id: '6',
            action: 'FINISH',
            params: 'Run final query',
            status: 'SUCCESS',
            confidence: 0.97,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:06',
            clarification: null,
            sql: 'SELECT s.name, COUNT(e.course_id) AS course_count FROM "Student" AS s JOIN "Enrollment" AS e ON s.id = e.student_id WHERE s.gpa > 8 GROUP BY s.name HAVING COUNT(e.course_id) > 3 ORDER BY course_count DESC LIMIT 20',
          },
        ],
        columns: ['student_name', 'course_count'],
        rows: [
          { student_name: 'Aisha', course_count: 4 },
          { student_name: 'Rohan', course_count: 5 },
          { student_name: 'Mina', course_count: 6 },
        ],
        ms: 142,
      },
      {
        id: 'q-uni-branch',
        title: 'Faculty per department',
        request: 'Faculty count by department with recovery from failed filter',
        status: 'active',
        updated: '2026-10-07 10:09',
        leaf: false,
        nodes: [
          {
            id: '1',
            parent_id: null,
            action: 'SELECT_TABLE',
            params: 'Department',
            status: 'SUCCESS',
            confidence: 0.96,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:00',
            clarification: null,
            sql: 'SELECT * FROM "Department" AS d',
          },
          {
            id: '2',
            parent_id: '1',
            action: 'JOIN',
            params: 'Faculty ON Department.id = Faculty.department_id',
            status: 'SUCCESS',
            confidence: 0.94,
            failure_reason: null,
            checkpoint_id: 'cp-2',
            created_at: '10:01',
            clarification: null,
            sql: 'SELECT * FROM "Department" AS d JOIN "Faculty" AS f ON d.id = f.department_id',
          },
          {
            id: '3',
            parent_id: '2',
            action: 'GROUP_BY',
            params: 'Department.name',
            status: 'SUCCESS',
            confidence: 0.92,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:02',
            clarification: null,
            sql: 'SELECT d.name AS department, COUNT(f.id) AS faculty_count FROM "Department" AS d JOIN "Faculty" AS f ON d.id = f.department_id GROUP BY d.name',
          },
          {
            id: '4',
            parent_id: '3',
            action: 'HAVING',
            params: 'COUNT(f.id) > 5',
            status: 'SUCCESS',
            confidence: 0.94,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:03',
            clarification: null,
            sql: 'SELECT d.name AS department, COUNT(f.id) AS faculty_count FROM "Department" AS d JOIN "Faculty" AS f ON d.id = f.department_id GROUP BY d.name HAVING COUNT(f.id) > 5',
          },
          {
            id: '5',
            parent_id: '4',
            action: 'FINISH',
            params: 'Run final query',
            status: 'SUCCESS',
            confidence: 0.97,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '10:04',
            clarification: null,
            sql: 'SELECT d.name AS department, COUNT(f.id) AS faculty_count FROM "Department" AS d JOIN "Faculty" AS f ON d.id = f.department_id GROUP BY d.name HAVING COUNT(f.id) > 5 ORDER BY faculty_count DESC LIMIT 20',
          },
        ],
        columns: ['department', 'faculty_count'],
        rows: [
          { department: 'CS', faculty_count: 9 },
          { department: 'Math', faculty_count: 7 },
        ],
        ms: 84,
      },
    ],
  },
  {
    id: 'db-library',
    name: 'library.sqlite',
    queries: [
      {
        id: 'q-lib-success',
        title: 'Books by author',
        request: 'List books by author ordered by publication year',
        status: 'success',
        updated: '2026-10-07 11:02',
        leaf: true,
        nodes: [
          {
            id: '1',
            parent_id: null,
            action: 'SELECT_TABLE',
            params: 'Books',
            status: 'SUCCESS',
            confidence: 0.95,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '11:00',
            clarification: null,
            sql: 'SELECT * FROM "Books" AS b',
          },
          {
            id: '2',
            parent_id: '1',
            action: 'JOIN',
            params: 'Authors ON Books.author_id = Authors.id',
            status: 'SUCCESS',
            confidence: 0.92,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '11:01',
            clarification: null,
            sql: 'SELECT * FROM "Books" AS b JOIN "Authors" AS a ON b.author_id = a.id',
          },
          {
            id: '3',
            parent_id: '2',
            action: 'GROUP_BY',
            params: 'Authors.name',
            status: 'SUCCESS',
            confidence: 0.9,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '11:02',
            clarification: null,
            sql: 'SELECT a.name AS author_name, COUNT(b.id) AS book_count FROM "Books" AS b JOIN "Authors" AS a ON b.author_id = a.id GROUP BY a.name',
          },
          {
            id: '4',
            parent_id: '3',
            action: 'ORDER_BY',
            params: 'book_count DESC',
            status: 'SUCCESS',
            confidence: 0.9,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '11:03',
            clarification: null,
            sql: 'SELECT a.name AS author_name, COUNT(b.id) AS book_count FROM "Books" AS b JOIN "Authors" AS a ON b.author_id = a.id GROUP BY a.name ORDER BY book_count DESC',
          },
          {
            id: '5',
            parent_id: '4',
            action: 'FINISH',
            params: 'Run final query',
            status: 'SUCCESS',
            confidence: 0.98,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '11:04',
            clarification: null,
            sql: 'SELECT a.name AS author_name, COUNT(b.id) AS book_count FROM "Books" AS b JOIN "Authors" AS a ON b.author_id = a.id GROUP BY a.name ORDER BY book_count DESC LIMIT 20',
          },
        ],
        columns: ['author_name', 'book_count'],
        rows: [
          { author_name: 'Maya Chen', book_count: 3 },
          { author_name: 'Leo Martin', book_count: 2 },
        ],
        ms: 131,
      },
      {
        id: 'q-lib-failed',
        title: 'Recently published books',
        request: 'Books published after 2020 but with a bad column name',
        status: 'failed',
        updated: '2026-10-07 11:10',
        leaf: true,
        nodes: [
          {
            id: '1',
            parent_id: null,
            action: 'SELECT_TABLE',
            params: 'Books',
            status: 'SUCCESS',
            confidence: 0.95,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '11:08',
            clarification: null,
            sql: 'SELECT * FROM "Books" AS b',
          },
          {
            id: '2',
            parent_id: '1',
            action: 'FILTER',
            params: 'published_year > 2020',
            status: 'FAILED',
            confidence: 0.62,
            failure_reason: 'COLUMN_INVALID',
            checkpoint_id: null,
            created_at: '11:09',
            clarification: null,
            sql: 'SELECT * FROM "Books" AS b WHERE b.published_year > 2020',
          },
        ],
        columns: [],
        rows: [],
        ms: 66,
      },
    ],
  },
  {
    id: 'db-hospital',
    name: 'hospital.sqlite',
    queries: [
      {
        id: 'q-hosp-success',
        title: 'Patients by department',
        request: 'Count patients per department and list the top ones',
        status: 'success',
        updated: '2026-10-07 12:03',
        leaf: true,
        nodes: [
          {
            id: '1',
            parent_id: null,
            action: 'SELECT_TABLE',
            params: 'Patients',
            status: 'SUCCESS',
            confidence: 0.96,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '12:00',
            clarification: null,
            sql: 'SELECT * FROM "Patients" AS p',
          },
          {
            id: '2',
            parent_id: '1',
            action: 'JOIN',
            params: 'Departments ON Patients.department_id = Departments.id',
            status: 'SUCCESS',
            confidence: 0.93,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '12:01',
            clarification: null,
            sql: 'SELECT * FROM "Patients" AS p JOIN "Departments" AS d ON p.department_id = d.id',
          },
          {
            id: '3',
            parent_id: '2',
            action: 'GROUP_BY',
            params: 'Departments.name',
            status: 'SUCCESS',
            confidence: 0.92,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '12:02',
            clarification: null,
            sql: 'SELECT d.name AS department, COUNT(p.id) AS patient_count FROM "Patients" AS p JOIN "Departments" AS d ON p.department_id = d.id GROUP BY d.name',
          },
          {
            id: '4',
            parent_id: '3',
            action: 'HAVING',
            params: 'COUNT(p.id) > 5',
            status: 'SUCCESS',
            confidence: 0.9,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '12:03',
            clarification: null,
            sql: 'SELECT d.name AS department, COUNT(p.id) AS patient_count FROM "Patients" AS p JOIN "Departments" AS d ON p.department_id = d.id GROUP BY d.name HAVING COUNT(p.id) > 5',
          },
          {
            id: '5',
            parent_id: '4',
            action: 'FINISH',
            params: 'Run final query',
            status: 'SUCCESS',
            confidence: 0.98,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '12:04',
            clarification: null,
            sql: 'SELECT d.name AS department, COUNT(p.id) AS patient_count FROM "Patients" AS p JOIN "Departments" AS d ON p.department_id = d.id GROUP BY d.name HAVING COUNT(p.id) > 5 ORDER BY patient_count DESC LIMIT 20',
          },
        ],
        columns: ['department', 'patient_count'],
        rows: [
          { department: 'Cardiology', patient_count: 12 },
          { department: 'Neurology', patient_count: 9 },
        ],
        ms: 119,
      },
      {
        id: 'q-hosp-branch',
        title: 'Emergency admissions by type',
        request: 'Emergency admissions grouped by patient type with failed filter branch',
        status: 'active',
        updated: '2026-10-07 12:09',
        leaf: false,
        nodes: [
          {
            id: '1',
            parent_id: null,
            action: 'SELECT_TABLE',
            params: 'Admissions',
            status: 'SUCCESS',
            confidence: 0.96,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '12:06',
            clarification: null,
            sql: 'SELECT * FROM "Admissions" AS a',
          },
          {
            id: '2',
            parent_id: '1',
            action: 'GROUP_BY',
            params: 'patient_type',
            status: 'SUCCESS',
            confidence: 0.93,
            failure_reason: null,
            checkpoint_id: 'cp-3',
            created_at: '12:07',
            clarification: null,
            sql: 'SELECT a.patient_type AS type, COUNT(a.id) AS admissions FROM "Admissions" AS a GROUP BY a.patient_type',
          },
          {
            id: '3',
            parent_id: '2',
            action: 'FILTER',
            params: 'severity > 5',
            status: 'FAILED',
            confidence: 0.7,
            failure_reason: 'COLUMN_INVALID',
            checkpoint_id: null,
            created_at: '12:08',
            clarification: null,
            sql: 'SELECT a.patient_type AS type, COUNT(a.id) AS admissions FROM "Admissions" AS a WHERE a.severity > 5 GROUP BY a.patient_type',
          },
          {
            id: '4',
            parent_id: '2',
            action: 'HAVING',
            params: 'COUNT(id) > 2',
            status: 'SUCCESS',
            confidence: 0.92,
            failure_reason: null,
            checkpoint_id: null,
            created_at: '12:09',
            clarification: 'Use the aggregated COUNT(id) check instead of a missing severity column',
            sql: 'SELECT a.patient_type AS type, COUNT(a.id) AS admissions FROM "Admissions" AS a GROUP BY a.patient_type HAVING COUNT(a.id) > 2',
          },
        ],
        columns: ['type', 'admissions'],
        rows: [
          { type: 'critical', admissions: 4 },
          { type: 'stable', admissions: 3 },
        ],
        ms: 73,
      },
    ],
  },
];

export const activeSession = {
  id: 'session-1',
  databaseId: 'db-university',
  queryId: 'q-uni-branch',
  request: 'Faculty count by department with recovery from failed filter',
  status: 'active',
};

export const graphNodes = queryCatalog
  .find((db) => db.id === activeSession.databaseId)
  ?.queries.find((query) => query.id === activeSession.queryId)
  ?.nodes ?? [];

export const finalSqlResult = {
  sql: graphNodes[graphNodes.length - 1]?.sql ?? '',
  columns: queryCatalog
    .find((db) => db.id === activeSession.databaseId)
    ?.queries.find((query) => query.id === activeSession.queryId)?.columns ?? [],
  rows: queryCatalog
    .find((db) => db.id === activeSession.databaseId)
    ?.queries.find((query) => query.id === activeSession.queryId)?.rows ?? [],
  row_count:
    (queryCatalog
      .find((db) => db.id === activeSession.databaseId)
      ?.queries.find((query) => query.id === activeSession.queryId)?.rows ?? []).length,
  execution_time_ms:
    queryCatalog
      .find((db) => db.id === activeSession.databaseId)
      ?.queries.find((query) => query.id === activeSession.queryId)?.ms ?? 0,
};

export const checkpoints = [
  {
    id: 'cp-1',
    state_id: '3',
    label: 'after_join',
  },
  {
    id: 'cp-2',
    state_id: '2',
    label: 'after_join',
  },
  {
    id: 'cp-3',
    state_id: '2',
    label: 'after_group_by',
  },
];
